language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install paper-icon-button
- bower install
- export DISPLAY=:99.0
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
    secure: yv7REPco7MGf9UTGXIpdCegtSihyhkr7KL3aG86CXAPFqtkins8Iou8d/G7nAIb8rYBEhW4Vr8KQgaorlZxqvQU2gOYj4Fx5BdzH/bDNHVaJTtHf7xU9/v8tJp13h5+we3hj+ps4TxYfEl5gzCWNVYlgSANALywtlGgHKgNpsDuO1bUhXvECz715Q1lRuQUUi4ihuln0KsEiYb8b0n2KuhIrWvkTtQYOfzNLcSjiHdKy0/he+kNB+xmewu39F3fYj6OZd3kNdLC1JuOHFdf3yJxhvb2GKaa5p5OiKK8DU3bFrNSrlICyOaMl5FPuMNXQrctdNSGLo8NFDqNSu52rQjvhidvNun1fgecS2ABLVpdh5yu6KxChPmddYgF55nVYJzPNszOvRuVB+weCbHbrEVg/r6MKBxAM3enJUA2c2iHkgLr8JoBQTIR4YziOIxWbix5vuP/DQTByhpiKZAGMJrqShvuPSVDvFkK5W4eVQaPkUmiahbfKdPcVoITpFOKiBPtXGVaYzCHRkN7MwU9YhrDU+y4OvUhPm9tiFM4rEfar6MWtwEnKom8V6PTTBrH6m+aDuxubSo4Ev4ziERmktrOKm1MvTdZKAG7keSiBrO40FlppSdLisBBPGu94wMeTnQZvk2XtqIo9XLXH8ukdJvtcMUYQSEM8djGZlMm36e0=
dd:
  secure: qPLbDzHRgcrletHHISbZglz8ylusVqxpVPrWhu1pstUi8JYV+ZT5mojdVrhEP5YFdjPSaDW7Koi+2e6ZdvFjZ8zDry+iuzfnUmARP/1n1DSBZ2rx8T9cH2/2hRVt8kfUndFn2PxId3iBrn5AsrPrBplZq9nSPlc+qDg7TPwv/p4KIkjbM/tlR5gqRGjP6G/awyOo7/6ZyWaJ661wL25jXazkozoRPmOCI8aDtjPCgSQurIibfCz9SK9QeJHt/0HQa3gPVgeIHL4L/uKaIniXcZYpaIqiKlbjQSJUD1du6vIFJbDAjTKr0TFIFcDWhndlG0L3QVe93pDVL+GmibtcQ30F/u469PoDlai+gQh9LqrNk4GF0DYBf0SG3KeanhJvdxV0GO9hjdDwbs2+JOgZJFROUELdHXSyyNM1FzjWlPABNhBWc9ewvmuZVMVvrfiro+yaWzJLyYzWVluQ6Cxy9qpaz5x/9QHEpwg3OCxB0sF+v8bwWo/d36tSLaYx9fIREJcY5/mbCybwcLuUNI58fDjNlqRYEKN/yk9tjrHQXvuuQpRbBaBz0p7wElmUO/uLW4zorzlx6NXzm8hh4yIWDS0TC1T4C6huaxxnUg0OdZ2ClhkKkEVuxRqvXQy7RnlCjXFHnhyKlYe2ni0E/6+Eoys3cJUxlx+wqfgF8jG491Y=
