language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install paper-icon-button
- bower install
- export DISPLAY=:99.0
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: mWrUJZj5arIdtHzDfvODhZ4saMksgbNWgyvKm8JiBJBdsQZPeLUADVf/GwuBTnrw3xp9jasQFhjRFVBXSW9xKxD/TsOLOW/fJJxys5h+9xKs3suYQHiwufH7RIkveR1ZSgmLKOxN1MlHHM1X5onzj89AOX8SfL/WRz1Qt8TCC5VSLkf0xlC6kxWZGQI88hom3zXT61WS3lWO65t3sZy59PLCZRi2mRDwd03jN/phoaBVVBhjeoXCyaGExvBBlJmdWC2SeqO5atx6xlNa5B/3lB0k8pI2nltAOI+Tsd+tCxMnJfTPMr9IHTB99Np0isY45ODJfE7xYlfSHKR1mwi6dB0zpgY15sj2KHh17uzUeCQuUOhX3JnpmzofOEuIW59X6R83L2/54R1U4/Ju+g+uf+VX58JlwBgkSHiByePI8inyEXtD9Pu/4J7/f5/4o8SmTT2mXDBsCN4Uj7gHoMqVylJMHfQTkOBbZXZD16DEgain2OCzSkTrxh8GqoglDAPSU09qAsBRHchfYjl2W3IvBGC+If3EejNskX6Ztnm6UJgz0PaxJa07R0aFAMAuaNdfpLf1BPet9zFveZ9cTG9teU20vnn0vchdc26Y6ex0ZcZRtjrSpd49GQQVcHAjwIUepP6xA4hLNauDjNHS52XW9jW8sNu/TSQebbLZiyWDlj0=
  - secure: MvivbCsqToe+Z6dhb7BbaRpqxoDoRE7KVaLBStNTfgS0rIrB9pVteShPe23zbC++34pbPLclXFoWKaVNblRgO1iOV5Mj1upwujAN/N85Qe/8YIYOvwRSJlxC90mMK8+Dxw3orCadxvLQWxVSqCqK9Ky2O+YT/f6Fe/t5Fjo5XQOXn2lbEdtG1pPSBnYMUQWUN4aS8NtbKlaSzrMvl1xxtufFdLsrvYesRDiaYZIyXZOVH5EYPVK+a9RwDAieXMESLJ1DTf8g5sg9yLV3Kev10OkPXhlPsf+y3Jqbu0t6wDS148GjMU2OrrQUikr4GNcs/qSe9rd8obziRe8M9JrWK+8PiGxbFSYnoIwSYT4gbKRiefu88vDkFdScHh6auvEfRArXzFZL2XUCILNAa+H+IoOO0f5fjtek83ghXXPfSSD7Kl8tEfMOpY6uX/qbO2aEQv7TyzqBW4ANiFg4Unupabd+uQXW/Bv0r8io2N4xBKjvnXyIuBT5jKFRD3S/MsAhidMTwT5LmzZCgHCRbnuyJKVLK5esZBa4CYFAizKB5KrnEinzsqo859is6Qf+d27mplXUko6Z/0r/dJ8fUkSJv6WPWkZaFfUQI49VKRtl2RKbbW95UecIFIe2ph6CNuWTTRRz3FvWBOaCBLbtLTI5Gocd1QG/vfF12TWX7yk/UQ0=
