language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install paper-icon-button
- bower install
- export DISPLAY=:99.0
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin local; fi
env:
  global:
  - secure: fN2adntLL31ymXw+1JAsfQdU00oHpcqLRlJxL7Tk3KR2a5HlqSWpdjDEsz9Rsu9dvHYo/lppSfu81FVli7dEcpGkX4MRZiLeOwhKC7qDNBV2ahnKm7q0frOb3kAErlriMI0etRW8WN/fNLhlcC8naR7RU8t4mrt/RpEO18uDHoxJIaGHMwIX/5nm6xeFnrwwxUiJr7zGE71lnwE9lQW54hUVgqIhxNfczz0uIW/3zGazEWXwcFo9PF23yaz4zOi1051hic5rrxd/gL1sdMX88hLCLZ8BtvRTzcLWYmRBbwc4m1R/Jfp7XbzRKtxt3/PUc6mKaHPkj9Ygj+wu0lEPZ3aV6Drz+kvGrHU/kHwzhNz5BqLBAF1gWkycWF/uqTBcAFmMuGwO4J5uxpeia7D6NCifOsuQaMOFQeVeJKKSfvaTN3NoLAym/8oGoK2BlNN15UkSyiO4lMg098ghOemGDKNjn5sNdgwndFbePUYpxJwiVBWogueIopMs0t5v2wNomjcQHUjJEPwwqOuqy1udsqvrsYcRwqqemo8M0Re4N9hz/Yv4o7ZY2DY/+robrXR0l7F6aX8YmQKyM52Vz1ony/zAQcA/wDA/tNqCwiWf1MLaBV9izFY/ePXa9vk/3ePY1Hhyd1gY6cxB16qgs4x91dQV+fUzHPbCJqCWQqe8juM=
  - secure: Q1Uri8+lMOIY/WSbQX0mpuwzegs+AmK3ad1mlDSxT8o61dGJPwSpD7hHvQfMvyE/fYa1sJdD2tZbLIhCGnSk69aPq//n4VzXB2UK8DAPLik4ABmepnBrd6M1rG/ahpS8oJitr6R0DHh5SEVX9jp13pb2IfSt0txhqR6LHYbn653rg4vHmBIZjrD+MsLPsumUevB7BRT74AQYJXUExq/l3q0UtWAkdKPacHYacwvpuYBzgiGjE1AKy6MYsjkburXus53p/YzJVmAU9Cee2zj191QyTEtC66R4NNv3IXh30AccHZ8XKYXiNcoThlwA1E6QTZZTJaxu5kk2Fj+x0m0lHOiE88WG9VMzzDLIOVLBINt+4rj+NFc5XZrRIwru/zNNeEcfX+9xPcaOyjc3d5KeuD7zahX5A5awonankGmVn1CDhgTp8i8omLTKSvaCswTYRQHeWP3pL07z2ed0rj2o9fIu4k4A3Wn6LhszO0nbNvgu/vqreFr+fETkcSo2GepQZ9ZmjBF4r447I94I++q9koTwh7mhqykJJUNT0pTFklsguhxm6qoKZoQIKObgLehPBsv9s4ZKwY7a0atqh9uMo4Iguu5MDopmreEmB7NUVTxeZPn5HWgoryGoOD/VTNo5r4iNjjW4xHbh35ZsfKYVfHwvT3SeE6UAncTAVu+cH80=
dd:
  secure: OjOuKUCmGlai1nRFPGwZLvSBLntT1E+4dsBhT92PzNN0ODW9zas6jbznQq8aveP914j/GKQ0PFnhRfi+amG+292dupvgMeW08mzlVpYBzeqD/dL3EG/e48lby6B8ZHBpljBeBFTYwiAZOk1crCO7MtmO+ip3fEN322/UJFc3Z9HKCxVowr9R2AOlfoqgZrZxKE3w45xAysuZKIpxr92AV5my3VauWe2cpMsJR6zNgZhuWqJIOH7Ret/5UzXWMIcOkElCRp7m8+d9igyKc1M3Pns7ZLOc9bPQTbhWhy0odykBJXBmRmq2ohfKnHa3j+CW/Ff394DU/prahnpifgi7lsibj/YD621mwu04NDyEFVxRqsE4RqHU0rWief3/+Vpz5KcOktNMic5R4XljXwpr+POyPP0tcyIPtgsfkTXH0s2rile7IP0qm4UsVdywxrXU58dkpbopLPhIph11+q4azt/aByzeojzakqzhXfx2WPIhw6EvcoxRI5M/+ypMEw5t516y7VTr5/5obmJ1ofEqSpceKs8fPNoS10jN1FqwlRv+4eOV1jonReUp885AMqZ30czSOlLrevlUAd396j9zWa5TXZQg33JEbrY+b0LRvmnVySOlssuUkPfq0hQa8jtB+HXICjT8ZZ5oGNk6w9db0GByvrwtspsT87xsAPD8efA=
